# Generated by Django 2.1.1 on 2019-04-29 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('post_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=10, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('region', models.CharField(max_length=100, verbose_name='町名・番地')),
                ('building_name', models.CharField(blank=True, max_length=50, verbose_name='アパート・マンション名')),
                ('company_name', models.CharField(blank=True, max_length=50, verbose_name='会社名')),
                ('phone_number', models.CharField(max_length=10, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '配送住所',
                'verbose_name_plural': '配送住所',
            },
        ),
    ]
