#! /bin/bash

APP="ec-app"
RUN_APP="docker-compose run --rm ${APP}"
MIGRATE="${RUN_APP} ./manage.py migrate"
BUILD_APP="docker-compose build"
UP_APP="docker-compose up -d"
DOWN_APP="docker-compose down"

case "$1" in
  "init")
    if [ ! -e '.env' ]; then
      cp .env.sample .env
    fi
    docker-compose down -v
    docker volume rm ec-pgdata | true
    docker volume rm ec-static | true
    docker volume rm ec-media | true
    $BUILD_APP
    $MIGRATE
    $RUN_APP ./manage.py loaddata shop_initial.json
    $RUN_APP ./manage.py createfactorydata
    ;;

  "up")
    $BUILD_APP
    $MIGRATE
    $UP_APP
    ;;

  "down")
    $DOWN_APP
    ;;
  
  "restart")
    $DOWN_APP
    $BUILD_APP
    $MIGRATE
    $UP_APP
    ;;

  "createsuperuser")
    $RUN_APP ./manage.py createsuperuser
    ;;

  "makemigrations")
    $RUN_APP ./manage.py makemigrations
    ;;

  "migrate")
    $MIGRATE
    ;;

  "initdb")
    docker-compose rm -s -f -v ec-postgres
    docker volume rm ec-pgdata | true
    $MIGRATE
    $RUN_APP ./manage.py loaddata shop_initial.json
    $RUN_APP ./manage.py createfactorydata
    ;;

  "login")
    docker exec -it $APP /bin/sh
    ;;

  "postgres")
    docker-compose exec ec-postgres psql -U postgres
    ;;

  "flake8")
    $RUN_APP flake8
    ;;

  "test")
    $RUN_APP ./manage.py test
    ;;
esac
