# Generated by Django 2.1.1 on 2019-04-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='名前')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('logo', models.ImageField(blank=True, max_length=320, upload_to='uploads/', verbose_name='ロゴ画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ブランド',
                'verbose_name_plural': 'ブランド',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='名前')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='商品名')),
                ('description', models.TextField(max_length=40000, verbose_name='商品説明')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, max_length=320, upload_to='uploads/', verbose_name='商品写真1')),
                ('image2', models.ImageField(blank=True, max_length=320, upload_to='uploads/', verbose_name='商品写真2')),
                ('image3', models.ImageField(blank=True, max_length=320, upload_to='uploads/', verbose_name='商品写真3')),
                ('price', models.IntegerField(default=1000, verbose_name='価格')),
                ('stock', models.IntegerField(default=1, verbose_name='在庫数')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Brand', verbose_name='ブランド名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
