# Generated by Django 2.1.1 on 2019-04-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=320, upload_to='uploads/', verbose_name='カテゴリー写真'),
        ),
    ]
