# Generated by Django 2.1.1 on 2019-04-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_popularproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product', unique=True, verbose_name='商品'),
        ),
    ]
