# Generated by Django 2.1.1 on 2019-05-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190420_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='origin2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='origin3',
        ),
    ]
