# Generated by Django 2.1.1 on 2019-04-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailmagazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailmagazine',
            options={'verbose_name': 'メールマガジン購読者リスト', 'verbose_name_plural': 'メールマガジン購読者リスト'},
        ),
    ]
