# Generated by Django 2.1.1 on 2019-04-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailmagazine', '0002_auto_20190428_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailMagazine',
        ),
    ]
