# Generated by Django 2.1.1 on 2019-05-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailmagazine', '0005_auto_20190429_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmagazine',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
