# Generated by Django 2.1.1 on 2019-04-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='お名前')),
                ('email', models.EmailField(max_length=240, verbose_name='メールアドレス')),
                ('title', models.CharField(max_length=240, verbose_name='お問合せタイトル')),
                ('content', models.TextField(max_length=4000, verbose_name='お問合せ内容')),
            ],
            options={
                'verbose_name': 'お問い合わせ内容',
                'verbose_name_plural': 'お問い合わせ内容',
            },
        ),
    ]
