# Generated by Django 2.1.1 on 2019-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_of_use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='タイトル')),
                ('description', models.CharField(max_length=240, verbose_name='ディスクリプション')),
                ('content', models.TextField(max_length=40000, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ご利用規約',
                'verbose_name_plural': 'ご利用規約',
            },
        ),
    ]
