# Generated by Django 2.1.1 on 2019-04-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190414_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mail_from_address',
            field=models.EmailField(default='fromexample@marushin.mn', max_length=254, verbose_name='メール送信元'),
        ),
        migrations.AddField(
            model_name='settings',
            name='mail_to_address',
            field=models.EmailField(default='toexample@marushin.mn', max_length=254, verbose_name='メール送信先'),
        ),
    ]
