# Generated by Django 2.1.1 on 2019-04-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190421_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='検索エンジンに登録する'),
        ),
    ]
