# Generated by Django 2.1.1 on 2019-04-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_settings_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delivery_fee',
            field=models.IntegerField(default=600, verbose_name='配送料金'),
        ),
    ]
